batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 11
  local_start: 2022-05-24_16:01:18
  local_stop: 2022-05-25_11:53:18
  program_exit: FAILURE
  stats:
    train_acc: 0.1837191526534178
    train_loss: 2.2557093865305453
    val_acc: 0.09545943454210203
    val_loss: 50.911672939753046
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 9
  num_params: 856650
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_std_cycliclr_503110/resnet56_3
param: param-files/LPResNet/RotSVHN/resnet56.yaml
scheduler:
  kwargs:
    base_lr: 0.01
    cycle_momentum: false
    max_lr: 0.1
  type: cyclic_lr
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
