batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-28_17:50:54
  local_stop: 2022-05-29_17:43:44
  program_exit: SUCCESS
  stats:
    train_acc: 0.8565052413190652
    train_loss: 0.41547215090390893
    val_acc: 0.6172787338660111
    val_loss: 1.5052665448950784
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  dropout: 0.2
  num_blocks: 3
  num_params: 270666
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_dropout_533616/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
