batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 25
  local_start: 2022-02-12_19:41:36
  local_stop: 2022-02-13_04:56:36
  program_exit: FAILURE
  stats:
    train_acc: 0.8445748491704375
    train_loss: 0.5251611509201641
    val_acc: 0.8253895888594164
    val_loss: 0.5785868094804195
model:
  act_func: relu
  batch_norm: false
  classname: SITHConClassifier
  layer_params:
  - buff_max: 6500
    channels: 35
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 50
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  - buff_max: 6500
    channels: 35
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 35
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  num_params: 72275
  out_classes: 35
  type: sithcon
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/SITH_train/sithcon_gsc_morlet_zscore_1095120/1
param: base-sithcon-params-2layer.yaml
train_data_dir: /geode2/home/u080/skarukas/Carbonate/SITH/data/SpeechCommands/processed_morlet_zscore/train
val_data_dir: /geode2/home/u080/skarukas/Carbonate/SITH/data/SpeechCommands/processed_morlet_zscore/val
