batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 12
  local_start: 2022-03-07_16:05:00
  local_stop: 2022-03-07_17:04:33
  program_exit: FAILURE
  stats:
    train_acc: 0.9638
    train_loss: 0.1161846059045444
    val_acc: 0.9653554313099042
    val_loss: 0.10934794292942927
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 5
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 1
  - in_channels: 10
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 40
    num_angles: 10
    out_channels: 10
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 1
  num_params: 4160
  out_classes: 10
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/lp_mnist_small_1153327/2
param: param-files/Deep-LP/log-polar-params-no-rot.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
