batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 6
  local_start: 2022-05-14_18:03:03
  local_stop: 2022-05-15_05:08:15
  program_exit: FAILURE
  stats:
    train_acc: 0.4812868530246779
    train_loss: 1.49692305489369
    val_acc: 0.27612169637369394
    val_loss: 4.745555906315559
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 9
  num_params: 856650
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_nofirst_layer_470915/resnet56_3
param: param-files/LPResNet/RotSVHN/resnet56.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
