batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 2
  local_start: 2022-05-11_17:48:53
  local_stop: 2022-05-11_18:41:52
  program_exit: FAILURE
  stats:
    train_acc: 0.18916521074470408
    train_loss: 2.237800543824771
    val_acc: 0.1958743085433313
    val_loss: 2.226827502543749
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    kernel_size: 7
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    spatial_trim: 4
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    spatial_trim: 4
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    spatial_trim: 4
    tau_max: 30
    tau_min: 1
    topk: 12
  num_params: 151882
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/rotsvhn/standard_464627/standard_lg_0
param: param-files/Deep-LP/RotSVHN/standard_lg.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
