batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 37
  local_start: 2022-05-19_21:58:51
  local_stop: 2022-05-20_21:33:50
  program_exit: FAILURE
  stats:
    train_acc: 0.9217623935357064
    train_loss: 0.21469557208375378
    val_acc: 0.8698524892440074
    val_loss: 0.4078514092096461
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270666
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_cc_477113/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
