batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 18
  local_start: 2022-05-14_18:03:03
  local_stop: 2022-05-15_05:34:46
  program_exit: FAILURE
  stats:
    train_acc: 0.8832714566499236
    train_loss: 0.3394390378710004
    val_acc: 0.863821450522434
    val_loss: 0.4034143084770434
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270666
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_nofirst_layer_470915/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
