batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-20_14:18:07
  local_stop: 2022-04-20_14:23:34
  program_exit: SUCCESS
  stats:
    train_acc: 0.9850317425569177
    train_loss: 0.046555458405569905
    val_acc: 0.9916557591623036
    val_loss: 0.02672410243985009
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size:
    - 7
    - 4
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 12
    out_channels: 20
    stride: 2
    tau_max: 8
    tau_min: 1
  - in_channels: 20
    k: 35
    kernel_size:
    - 5
    - 4
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 12
    out_channels: 20
    stride: 2
    tau_max: 8
    tau_min: 1
  num_params: 9146
  out_classes: 6
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/angle_invariance_tests/angle_tests_fullpool_stride2_377602/30deg_rotations_0
param: param-files/Deep-LP/MNIST/rotation_test/30deg_rotations.yaml
train_data_dir:
  kwargs:
    allowed_targets:
    - 1
    - 2
    - 3
    - 8
    - 0
    - 6
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    allowed_targets:
    - 1
    - 2
    - 3
    - 8
    - 0
    - 6
    root: data
    train: false
  type: FastMNIST
