batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-06_18:33:35
  local_stop: 2022-04-06_19:10:45
  program_exit: SUCCESS
  stats:
    train_acc: 0.748260556621881
    train_loss: 0.7062320809141612
    val_acc: 0.7010782747603834
    val_loss: 0.8633985676514074
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    k: 50
    kernel_size:
    - 5
    - 5
    ntau: 8
    num_angles: 8
    out_channels: 16
    stride: 2
    tau_max: 16
    tau_min: 1
    theta_pooling: 2
  - in_channels: 16
    k: 50
    kernel_size:
    - 5
    - 5
    ntau: 8
    num_angles: 8
    out_channels: 32
    stride: 2
    tau_max: 16
    tau_min: 1
    theta_pooling: 2
  - in_channels: 32
    k: 50
    kernel_size:
    - 5
    - 5
    ntau: 8
    num_angles: 8
    out_channels: 64
    stride: 2
    tau_max: 16
    tau_min: 1
    theta_pooling: 2
  num_params: 73050
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/local_filter_2_1263234/local_16_8_0
param: param-files/Deep-LP/CIFAR10/ab_tests/local_16_8.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
