# experiment represented by param file
model: 
  type: sithcon
  dropout:
  - 0
  - 0.2
  - 0.5
optimizer:
  type: adam
  params:
    lr: 0.0001
num_epochs: 40
batch_size: 64
train_data_dir: "data/example_dataset"
val_data_dir: "data/example_dataset"