# experiment represented by param file
model: 
  type: sithcon
  dropout:
  - 0
  - 0.2
  - 0.5
optimizer:
  type: adam
  learning_rate: 0.0001
train_data_dir: "data/example_dataset"
train_data_dir: "data/example_dataset"