model: 
  type: lp_resnet
  block: DeepLPBlock
  num_blocks: 3
  act_func: relu
  out_classes: 10
optimizer:
  type: adam
  params:
    weight_decay: 0.01
    lr: 0.001
num_epochs: 40
batch_size: 8
train_data_dir: 
  type: SVHN
  kwargs:
    root: "data"
    split: train
val_data_dir: 
  type: SVHN
  kwargs:
    root: "data"
    split: test
collate: batch
