batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-28_17:55:30
  local_stop: 2022-05-29_17:51:16
  program_exit: SUCCESS
  stats:
    train_acc: 0.8972483074907185
    train_loss: 0.2960110862211422
    val_acc: 0.8842962507682852
    val_loss: 0.3318337204294553
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270666
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
    weight_decay: 0.01
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_weight_decay_533620/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
