batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 13
  local_start: 2022-05-22_16:07:20
  local_stop: 2022-05-23_15:39:16
  program_exit: FAILURE
  stats:
    train_acc: 0.8509090412753877
    train_loss: 0.4197215370654357
    val_acc: 0.8372387830362631
    val_loss: 0.4959161723795053
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 9
  num_params: 856650
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_standardized_483955/resnet56_3
param: param-files/LPResNet/RotSVHN/resnet56.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
