batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 26
  local_start: 2022-04-11_01:24:22
  local_stop: 2022-04-11_10:10:06
  program_exit: FAILURE
  stats:
    train_acc: 0.9201255598208573
    train_loss: 0.22460540511805663
    val_acc: 0.8469448881789138
    val_loss: 0.4863976714805292
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    k: 50
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 8
    num_angles: 8
    out_channels: 32
    tau_max: 8
    tau_min: 1
    theta_pooling: 2
  - in_channels: 32
    k: 50
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 8
    num_angles: 8
    out_channels: 64
    tau_max: 8
    tau_min: 1
    theta_pooling: 2
  - in_channels: 64
    k: 50
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 8
    num_angles: 8
    out_channels: 128
    stride: 2
    tau_max: 8
    tau_min: 1
    theta_pooling: 2
  - in_channels: 128
    k: 50
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 8
    num_angles: 8
    out_channels: 256
    stride: 2
    tau_max: 8
    tau_min: 1
    theta_pooling: 2
  - in_channels: 256
    k: 50
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 8
    num_angles: 8
    out_channels: 512
    stride: 2
    tau_max: 8
    tau_min: 1
    theta_pooling: 2
  num_params: 4724522
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 60
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/local_gigantic_1284343/local_8_8_5layer_s1_0
param: param-files/Deep-LP/CIFAR10/ab_tests/local_8_8_5layer_s1.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
