batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-19_17:08:47
  local_stop: 2022-04-19_18:20:58
  program_exit: SUCCESS
  stats:
    train_acc: 0.9899846760070052
    train_loss: 0.03023414597425556
    val_acc: 0.9913285340314136
    val_loss: 0.028113969738067356
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size: 7
    localization: gaussian
    ntau: 8
    num_angles: 12
    out_channels: 20
    tau_max: 8
    tau_min: 1
  - in_channels: 20
    k: 35
    kernel_size: 5
    localization: gaussian
    ntau: 8
    num_angles: 12
    out_channels: 20
    tau_max: 8
    tau_min: 1
  num_params: 11566
  out_classes: 6
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/angle_tests_372483/30deg_rotations_0
param: param-files/Deep-LP/MNIST/rotation_test/30deg_rotations.yaml
train_data_dir:
  kwargs:
    allowed_targets:
    - 1
    - 2
    - 3
    - 8
    - 0
    - 6
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    allowed_targets:
    - 1
    - 2
    - 3
    - 8
    - 0
    - 6
    root: data
    train: false
  type: FastMNIST
