batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 1
  local_start: 2022-05-16_18:00:32
  local_stop: 2022-05-16_18:52:16
  program_exit: FAILURE
  stats:
    train_acc: 0.2421336774944104
    train_loss: 2.129620971191565
    val_acc: 0.3821670227920228
    val_loss: 1.7021582908822261
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/debug_svhn_minus_472875/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: test
  type: SVHN
