batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-03-18_23:37:55
  local_stop: 2022-03-19_02:54:25
  program_exit: SUCCESS
  stats:
    train_acc: 0.9926333333333334
    train_loss: 0.02048812649486887
    val_acc: 0.9806309904153354
    val_loss: 0.07642747436920691
model:
  act_func: relu
  batch_norm: true
  classname: DeepLogPolarClassifier
  layer_params:
  - gaussian_sharpness: 2
    in_channels: 1
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 4
    tau_max: 60
    tau_min: 1
    theta_pooling: 4
  - gaussian_sharpness: 2
    in_channels: 20
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 4
    tau_max: 60
    tau_min: 1
    theta_pooling: 4
  num_params: 12450
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/lp_mnist_combo_quick_4_med_1193872/combo-quick-4-med_0
param: param-files/Deep-LP/combo-quick-4-med.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
