model: 
  type: logpolar
  layer_params:
    # layer 1
    - in_channels: 1
      out_channels: 20
      tau_min: 1
      tau_max: 60
      ntau: 40
      k: 35
      kernel_size: 
        - 5
        - 5
      stride: 4
      num_angles: 10
      theta_pooling: 4
      localization: gaussian
      gaussian_sharpness: 2
    # layer 2
    - in_channels: 20
      out_channels: 20
      tau_min: 1
      tau_max: 60
      ntau: 40
      k: 35
      kernel_size: 
        - 5
        - 5
      stride: 4
      num_angles: 10
      theta_pooling: 4
      localization: gaussian
      gaussian_sharpness: 2
  batch_norm: True
  act_func: relu
  out_classes: 10
  output: max
optimizer:
  type: adam
  params:
    lr: 0.001
num_epochs: 40
batch_size: 32
train_data_dir: 
  type: TransformedMNIST
  kwargs:
    root: data
    train: True
    max_translate: 20
val_data_dir: 
  type: FastMNIST
  kwargs:
    root: "data"
    train: False
collate: batch
