batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 16
  local_start: 2022-05-13_13:59:27
  local_stop: 2022-05-14_01:36:37
  program_exit: FAILURE
  stats:
    train_acc: 0.6927413190652981
    train_loss: 0.9036002070965381
    val_acc: 0.6824293177627535
    val_loss: 0.9377166118997149
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270410
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_sub_imean_468517/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
