batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 10
  local_start: 2022-05-16_22:49:22
  local_stop: 2022-05-17_16:52:51
  program_exit: FAILURE
  stats:
    train_acc: 0.67760428041057
    train_loss: 0.9249479911536415
    val_acc: 0.08166871542716657
    val_loss: 12.47817662862011
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 9
  num_params: 856650
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_473006/resnet56_3
param: param-files/LPResNet/RotSVHN/resnet56.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
