batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 36
  local_start: 2022-04-03_01:07:18
  local_stop: 2022-04-03_06:58:59
  program_exit: FAILURE
  stats:
    train_acc: 0.8100007997440819
    train_loss: 0.5314623884051104
    val_acc: 0.7138578274760383
    val_loss: 0.8352994408470373
model:
  act_func: leaky
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 26
    num_angles: 20
    out_channels: 16
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 16
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 26
    num_angles: 20
    out_channels: 32
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - in_channels: 32
    k: 35
    kernel_size:
    - 5
    - 5
    ntau: 26
    num_angles: 20
    out_channels: 64
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  num_params: 113370
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/batchnorm_and_act_ab_1240941/leaky_1
param: param-files/Deep-LP/CIFAR10/ab_tests/leaky.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
