batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 0
  local_start: 2022-02-15_10:31:18
  local_stop: 2022-02-15_12:22:28
  program_exit: FAILURE
model:
  act_func: relu
  batch_norm: false
  classname: SITHConClassifier
  layer_params:
  - buff_max: 6500
    channels: 128
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 50
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  - buff_max: 6500
    channels: 64
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 128
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  - buff_max: 6500
    channels: 35
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 64
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  num_params: 410555
  out_classes: 35
  type: sithcon
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/SITH_train/sithcon_gsc_cqt_new_1098838/2
param: base-sithcon-params-vlg-cqt.yaml
train_data_dir: /geode2/home/u080/skarukas/Carbonate/SITH/data/SpeechCommands/processed_cqt_zscore/train
val_data_dir: /geode2/home/u080/skarukas/Carbonate/SITH/data/SpeechCommands/processed_cqt_zscore/val
