batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 26
  local_start: 2022-05-28_17:50:54
  local_stop: 2022-05-30_16:44:58
  program_exit: FAILURE
  stats:
    train_acc: 0.1892607556234986
    train_loss: 2.2398727039995086
    val_acc: 0.077519975414874
    val_loss: 28.960573585764646
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  dropout: 0.2
  num_blocks: 9
  num_params: 856650
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_dropout_533616/resnet56_3
param: param-files/LPResNet/RotSVHN/resnet56.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
