batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 23
  local_start: 2022-05-22_16:07:20
  local_stop: 2022-05-23_15:10:10
  program_exit: FAILURE
  stats:
    train_acc: 0.9077309456213147
    train_loss: 0.25809306652617753
    val_acc: 0.8702366318377381
    val_loss: 0.43254389374426533
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_standardized_483955/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
