batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 13
  local_start: 2022-04-22_12:07:43
  local_stop: 2022-04-22_14:01:32
  program_exit: FAILURE
  stats:
    train_acc: 0.9780833333333333
    train_loss: 0.06812443289829728
    val_acc: 0.9805311501597445
    val_loss: 0.06253451600666352
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size: 7
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 12
    out_channels: 64
    tau_max: 8
    tau_min: 1
  - in_channels: 64
    k: 35
    kernel_size: 5
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 12
    out_channels: 64
    tau_max: 8
    tau_min: 1
  num_params: 110474
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/full_invariance_383699/fullpooling-med_0
param: param-files/Deep-LP/MNIST/fullpooling-med.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
