batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 32
  local_start: 2022-05-16_22:48:08
  local_stop: 2022-05-17_15:12:36
  program_exit: FAILURE
  stats:
    train_acc: 0.9303505535055351
    train_loss: 0.21395502031527935
    val_acc: 0.8787838319088319
    val_loss: 0.4049700155668989
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270666
  out_classes: 8
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_minus_473002/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: test
  type: SVHN
