batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-28_17:55:32
  local_stop: 2022-05-30_09:59:50
  program_exit: SUCCESS
  stats:
    train_acc: 0.8945730508844726
    train_loss: 0.3032664620729746
    val_acc: 0.8867931776275353
    val_loss: 0.32253678311483214
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
    weight_decay: 0.01
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_weight_decay_533620/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
