batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 17
  local_start: 2022-04-29_22:38:31
  local_stop: 2022-04-30_07:09:38
  program_exit: FAILURE
  stats:
    train_acc: 0.9896166666666667
    train_loss: 0.03261696012233853
    val_acc: 0.9898
    val_loss: 0.03293380830281385
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    kernel_size: 7
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    tau_max: 30
    tau_min: 1
    topk: 12
  num_params: 148746
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist_r/bilinear_ntau20_new_427144/30deg_rotations_tk12_lg_1
param: param-files/Deep-LP/MNIST/rotation_test/30deg_rotations_tk12_lg.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
