model: 
  type: logpolar
  layer_params:
    # layer 1
    - in_channels: 1
      out_channels: 32
      tau_min: 1
      tau_max: 8
      ntau: 8
      num_angles: 12
      topk: 12
      k: 35
      kernel_size: 7
      localization: gaussian
      lp_version: 2
    # layer 2
    - in_channels: 32
      out_channels: 64
      tau_min: 1
      tau_max: 8
      ntau: 8
      num_angles: 12
      topk: 12
      k: 35
      kernel_size: 5
      localization: gaussian
      lp_version: 2
    # layer 3
    - in_channels: 32
      out_channels: 64
      tau_min: 1
      tau_max: 8
      ntau: 8
      num_angles: 12
      topk: 12
      k: 35
      kernel_size: 5
      localization: gaussian
      lp_version: 2
  dropout: 0.2
  batch_norm: False
  act_func: relu
  out_classes: 10
  output: max
optimizer:
  type: adam
  params:
    lr: 0.001
num_epochs: 40
batch_size: 32
train_data_dir: 
  type: RotMNIST
  kwargs:
    root: "data"
    train: True
val_data_dir: 
  type: RotMNIST
  kwargs:
    root: "data"
    train: False
collate: batch
