batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 1
  local_start: 2022-05-01_13:17:03
  local_stop: 2022-05-01_13:25:59
  program_exit: FAILURE
  stats:
    train_acc: 0.7773166666666667
    train_loss: 0.680763808053111
    val_acc: 0.8907
    val_loss: 0.35346085682958367
model:
  act_func: relu
  batch_norm: false
  channels:
  - 1
  - 32
  - 64
  - 128
  - 256
  classname: SingleLPClassifier
  dropout: 0.2
  filter_sizes:
  - 7
  - 5
  - 3
  - 3
  lp_params:
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    tau_max: 30
    tau_min: 1
  num_params: 424458
  out_classes: 10
  output: max
  type: single_lp
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Single_LP_train/mnist/simple_432773/single_lp_2_0
param: param-files/Single_LP/MNIST/single_lp_2.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
