batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-20_13:29:05
  local_stop: 2022-04-20_13:49:28
  program_exit: SUCCESS
  stats:
    train_acc: 0.9979750437828371
    train_loss: 0.00643822157208927
    val_acc: 0.993782722513089
    val_loss: 0.020315998156250112
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size:
    - 7
    - 4
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 4
    out_channels: 20
    tau_max: 8
    tau_min: 1
    theta_pooling: 1
  - in_channels: 20
    k: 35
    kernel_size:
    - 5
    - 4
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 4
    out_channels: 20
    tau_max: 8
    tau_min: 1
    theta_pooling: 1
  num_params: 10706
  out_classes: 6
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/angle_tests_half_pooling_376083/90deg_rotations_1
param: param-files/Deep-LP/MNIST/rotation_test/90deg_rotations.yaml
train_data_dir:
  kwargs:
    allowed_targets:
    - 1
    - 2
    - 3
    - 8
    - 0
    - 6
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    allowed_targets:
    - 1
    - 2
    - 3
    - 8
    - 0
    - 6
    root: data
    train: false
  type: FastMNIST
