batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 13
  local_start: 2022-02-13_11:36:28
  local_stop: 2022-02-13_21:03:39
  program_exit: FAILURE
  stats:
    train_acc: 0.848934766214178
    train_loss: 0.5079249799031017
    val_acc: 0.8452903956675508
    val_loss: 0.5321586777766546
model:
  act_func: relu
  batch_norm: false
  classname: SITHConClassifier
  layer_params:
  - buff_max: 6500
    channels: 50
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 50
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  - buff_max: 6500
    channels: 50
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 50
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  - buff_max: 6500
    channels: 35
    dilation: 2
    dt: 1
    g: 0.0
    in_features: 50
    k: 35
    kernel_width: 23
    ntau: 400
    tau_max: 4000
    tau_min: 1
  num_params: 163005
  out_classes: 35
  type: sithcon
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/SITH_train/sithcon_gsc_lg_2dataset_1095269/1
param: base-sithcon-params-lg-morlet.yaml
train_data_dir: /geode2/home/u080/skarukas/Carbonate/SITH/data/SpeechCommands/processed_morlet_zscore/train
val_data_dir: /geode2/home/u080/skarukas/Carbonate/SITH/data/SpeechCommands/processed_morlet_zscore/val
