batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 20
  local_start: 2022-05-16_22:48:11
  local_stop: 2022-05-17_15:56:59
  program_exit: FAILURE
  stats:
    train_acc: 0.8101675967498592
    train_loss: 0.5459854283364982
    val_acc: 0.7917111823361823
    val_loss: 0.6172470355379372
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465994
  out_classes: 8
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_minus_473002/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: test
  type: SVHN
