batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 28
  local_start: 2022-05-16_22:49:16
  local_stop: 2022-05-17_15:28:40
  program_exit: FAILURE
  stats:
    train_acc: 0.8896320157239572
    train_loss: 0.31328807375135437
    val_acc: 0.848340503995083
    val_loss: 0.4648549234978152
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270666
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_473006/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
