batch_size: 64
device: cpu
execution:
  epochs_completed: 0
  local_start: 2022-02-01_13:42:26
  local_stop: 2022-02-01_13:42:26
  program_exit: FAILURE
model:
  dropout:
  - 0
  - 0.2
  - 0.5
  type: sithcon
num_epochs: 40
optimizer:
  params:
    lr: 0.0001
  type: adam
out_dir: out/2022-02-01_13:42:26
param: example-params.yaml
train_data_dir: data/example_dataset
val_data_dir: data/example_dataset
