batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 11
  local_start: 2022-05-14_18:03:03
  local_stop: 2022-05-15_05:29:51
  program_exit: FAILURE
  stats:
    train_acc: 0.8556862852151125
    train_loss: 0.41935463640872167
    val_acc: 0.8592501536570375
    val_loss: 0.4164629186667515
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_nofirst_layer_470915/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
