batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 37
  local_start: 2022-04-02_13:17:55
  local_stop: 2022-04-02_17:12:22
  program_exit: FAILURE
  stats:
    train_acc: 0.8498680422264875
    train_loss: 0.4254142794321915
    val_acc: 0.7574880191693291
    val_loss: 0.7316256737271056
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 3
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 20
    num_angles: 30
    out_channels: 16
    stride: 2
    tau_max: 20
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 6
  - in_channels: 16
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 20
    num_angles: 30
    out_channels: 32
    stride: 2
    tau_max: 20
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 6
  - in_channels: 32
    k: 35
    kernel_size:
    - 7
    - 7
    ntau: 20
    num_angles: 30
    out_channels: 64
    stride: 2
    tau_max: 20
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 6
  num_params: 156762
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/ntheta_ab_7x7_1240019/theta30_2
param: param-files/Deep-LP/CIFAR10/theta30.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
