model: 
  type: logpolar
  layer_params:
    # layer 1
    - in_channels: 3
      out_channels: 16
      tau_min: 1
      tau_max: 40
      ntau: 26
      k: 35
      kernel_size: 
        - 5
        - 5
      num_angles: 20
      stride: 2
      theta_pooling: 4
      tau_pooling: 4
      localization: gaussian
      gaussian-sharpness: 2
    # layer 2
    - in_channels: 16
      out_channels: 32
      tau_min: 1
      tau_max: 40
      ntau: 26
      k: 35
      kernel_size: 
        - 5
        - 5
      num_angles: 20
      stride: 2
      theta_pooling: 4
      tau_pooling: 4
      localization: gaussian
      gaussian-sharpness: 2
    # layer 3
    - in_channels: 32
      out_channels: 64
      tau_min: 1
      tau_max: 40
      ntau: 26
      k: 35
      kernel_size: 
        - 5
        - 5
      num_angles: 20
      stride: 2
      theta_pooling: 4
      tau_pooling: 4
      localization: gaussian
      gaussian-sharpness: 2
  dropout: 0.2
  batch_norm: False
  act_func: relu
  out_classes: 10
  output: max
optimizer:
  type: adam
  params:
    lr: 0.001
num_epochs: 40
batch_size: 32
train_data_dir: 
  type: CIFAR10
  kwargs:
    root: data
    train: True
    download: True
val_data_dir: 
  type: CIFAR10
  kwargs:
    root: data
    train: False
    download: True
collate: batch
