batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 27
  local_start: 2022-05-24_15:35:35
  local_stop: 2022-05-26_14:45:33
  program_exit: FAILURE
  stats:
    train_acc: 0.9182681808255078
    train_loss: 0.2362552633758871
    val_acc: 0.8865242778119238
    val_loss: 0.3373034473908492
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 9
  num_params: 856650
  out_classes: 10
  pooling: average
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_std_avg_503081/resnet56_3
param: param-files/LPResNet/RotSVHN/resnet56.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
