batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-08_20:36:33
  local_stop: 2022-04-09_03:15:35
  program_exit: SUCCESS
  stats:
    train_acc: 0.7876679462571977
    train_loss: 0.599154409381036
    val_acc: 0.7387180511182109
    val_loss: 0.7525678840689004
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - gaussian_sharpness: 3
    in_channels: 3
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 26
    num_angles: 20
    out_channels: 16
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - gaussian_sharpness: 3
    in_channels: 16
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 26
    num_angles: 20
    out_channels: 32
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - gaussian_sharpness: 3
    in_channels: 32
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 26
    num_angles: 20
    out_channels: 64
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  num_params: 113370
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/localization_fixed_1282016/gaussian_3_2
param: param-files/Deep-LP/CIFAR10/ab_tests/gaussian_3.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
