batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 1
  local_start: 2022-05-16_18:00:32
  local_stop: 2022-05-16_18:31:36
  program_exit: FAILURE
  stats:
    train_acc: 0.40061894461309144
    train_loss: 1.690831070886964
    val_acc: 0.676994301994302
    val_loss: 1.008869980708656
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270666
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/debug_svhn_minus_472875/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    allowed_targets:
    - 0
    - 1
    - 2
    - 3
    - 4
    - 5
    - 7
    - 8
    root: data
    split: test
  type: SVHN
