batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-24_15:35:35
  local_stop: 2022-05-25_14:42:00
  program_exit: SUCCESS
  stats:
    train_acc: 0.9109248744267308
    train_loss: 0.25716509563829415
    val_acc: 0.8777658266748617
    val_loss: 0.3585056689167601
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 270666
  out_classes: 10
  pooling: average
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_std_avg_503081/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
