batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 26
  local_start: 2022-05-06_10:15:29
  local_stop: 2022-05-06_13:16:58
  program_exit: FAILURE
  stats:
    train_acc: 0.9857666666666667
    train_loss: 0.04351135743949345
    val_acc: 0.983
    val_loss: 0.05291562983971671
model:
  act_func: relu
  batch_norm: true
  channels:
  - 1
  - 32
  - 64
  - 128
  classname: SingleLPClassifier
  dropout: 0.2
  filter_sizes:
  - 7
  - 5
  - 3
  lp_params:
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    tau_max: 30
    tau_min: 1
  num_params: 128458
  out_classes: 10
  output: max
  type: single_lp
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Single_LP_train/mnist_r/simple_new_447989/single_lp_2_bn_1
param: param-files/Single_LP/MNIST/single_lp_2_bn.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: MNIST_R
val_data_dir:
  kwargs:
    root: data
    train: false
  type: MNIST_R
