model: 
  type: logpolar
  layer_params:
    # layer 1
    - in_channels: 3
      out_channels: 32
      tau_min: 1
      tau_max: 60
      ntau: 26
      kernel_size: 7
      num_angles: 12
      topk: 12
      lp_version: bilinear
    # layer 2
    - in_channels: 32
      out_channels: 64
      tau_min: 1
      tau_max: 60
      ntau: 26
      kernel_size: 5
      num_angles: 12
      topk: 12
      lp_version: bilinear
    # layer 3
    - in_channels: 64
      out_channels: 64
      tau_min: 1
      tau_max: 60
      ntau: 26
      kernel_size: 5
      num_angles: 12
      topk: 12
      lp_version: bilinear
  dropout: 0.2
  batch_norm: False
  act_func: relu
  out_classes: 10
  output: max
optimizer:
  type: adam
  params:
    lr: 0.001
num_epochs: 40
batch_size: 8
train_data_dir: 
  type: CIFAR10
  kwargs:
    root: data
    train: True
    download: True
val_data_dir: 
  type: CIFAR10
  kwargs:
    root: data
    train: False
    download: True
collate: batch
