batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-03_13:39:01
  local_stop: 2022-05-03_19:26:36
  program_exit: SUCCESS
  stats:
    train_acc: 0.97625
    train_loss: 0.07344605225104217
    val_acc: 0.9467970249520153
    val_loss: 0.15935655891590217
model:
  act_func: relu
  batch_norm: true
  channels:
  - 1
  - 32
  - 64
  - 32
  classname: SingleLPClassifier
  dropout: 0.2
  filter_sizes:
  - 5
  - 3
  - 3
  lp_params:
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    tau_max: 30
    tau_min: 1
  num_params: 38378
  out_classes: 10
  output: max
  type: single_lp
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Single_LP_train/mnist/simple_new_442482/single_lp_1_bn_0
param: param-files/Single_LP/MNIST/single_lp_1_bn.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: RotMNIST
