batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 13
  local_start: 2022-05-16_17:09:54
  local_stop: 2022-05-17_16:39:29
  program_exit: FAILURE
  stats:
    train_acc: 0.18912426293950643
    train_loss: 2.237142190893656
    val_acc: 0.19552858020897357
    val_loss: 197.83051496766137
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 9
  num_params: 856650
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_472859/resnet56_3
param: param-files/LPResNet/RotSVHN/resnet56.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
