batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 22
  local_start: 2022-05-16_17:09:56
  local_stop: 2022-05-17_15:11:01
  program_exit: FAILURE
  stats:
    train_acc: 0.8590167067045207
    train_loss: 0.4035733904612059
    val_acc: 0.8378534111862324
    val_loss: 0.46957857086473176
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_472859/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
