batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 34
  local_start: 2022-04-04_22:14:21
  local_stop: 2022-04-05_07:00:54
  program_exit: FAILURE
  stats:
    train_acc: 0.8186980166346769
    train_loss: 0.5139296051884643
    val_acc: 0.7467052715654952
    val_loss: 0.7368765110120225
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - gaussian-sharpness: 2
    in_channels: 3
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 26
    num_angles: 20
    out_channels: 16
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - gaussian-sharpness: 2
    in_channels: 16
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 26
    num_angles: 20
    out_channels: 32
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  - gaussian-sharpness: 2
    in_channels: 32
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 26
    num_angles: 20
    out_channels: 64
    stride: 2
    tau_max: 40
    tau_min: 1
    tau_pooling: 4
    theta_pooling: 4
  num_params: 113370
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/cifar10/localization_2_ab_1247858/gaussian_2_2
param: param-files/Deep-LP/CIFAR10/ab_tests/gaussian_2.yaml
train_data_dir:
  kwargs:
    download: true
    root: data
    train: true
  type: CIFAR10
val_data_dir:
  kwargs:
    download: true
    root: data
    train: false
  type: CIFAR10
