batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 10
  local_start: 2022-05-13_14:01:15
  local_stop: 2022-05-14_01:34:40
  program_exit: FAILURE
  stats:
    train_acc: 0.44526643371915264
    train_loss: 1.5873608369771557
    val_acc: 0.4250537799631223
    val_loss: 1.6519437710895961
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465290
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_1_n1_468521/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
