batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-03-17_03:25:38
  local_stop: 2022-03-17_09:07:14
  program_exit: SUCCESS
  stats:
    train_acc: 0.99545
    train_loss: 0.013272460239367472
    val_acc: 0.985423322683706
    val_loss: 0.05593316466282001
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  layer_params:
  - gaussian_sharpness: 2
    in_channels: 1
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 2
  - gaussian_sharpness: 2
    in_channels: 20
    k: 35
    kernel_size:
    - 5
    - 5
    localization: gaussian
    ntau: 40
    num_angles: 10
    out_channels: 20
    stride: 2
    tau_max: 60
    tau_min: 1
    theta_pooling: 2
  num_params: 13570
  out_classes: 10
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/lp_mnist_local_pooling_ab_1189805/1
param: param-files/Deep-LP/gaussian-med.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
