batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-04_16:51:56
  local_stop: 2022-05-04_18:54:19
  program_exit: SUCCESS
  stats:
    train_acc: 0.9944666666666667
    train_loss: 0.018112343979630685
    val_acc: 0.9886
    val_loss: 0.037540992729389384
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    kernel_size: 7
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 32
    spatial_trim: 4
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    spatial_trim: 4
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 20
    num_angles: 12
    out_channels: 64
    spatial_trim: 4
    tau_max: 30
    tau_min: 1
    topk: 12
  num_params: 148746
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/lg_trim_new_445226/standard_lg_trim4_2
param: param-files/Deep-LP/MNIST/rotation_test/standard_lg_trim4.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
