batch_size: 32
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-22_12:41:46
  local_stop: 2022-04-22_13:14:34
  program_exit: SUCCESS
  stats:
    train_acc: 0.9735833333333334
    train_loss: 0.08400173346586526
    val_acc: 0.9750399361022364
    val_loss: 0.07708799766864592
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    k: 35
    kernel_size:
    - 7
    - 4
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 4
    out_channels: 20
    tau_max: 8
    tau_min: 1
  - in_channels: 20
    k: 35
    kernel_size:
    - 5
    - 4
    localization: gaussian
    lp_version: 2
    ntau: 8
    num_angles: 4
    out_channels: 20
    tau_max: 8
    tau_min: 1
  num_params: 9230
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/full_mnist_angle_invariance/small_384209/90deg_rotations_1
param: param-files/Deep-LP/MNIST/rotation_test/90deg_rotations.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
