batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-05-28_17:50:54
  local_stop: 2022-05-30_09:54:22
  program_exit: SUCCESS
  stats:
    train_acc: 0.8148067263594672
    train_loss: 0.5376132001116348
    val_acc: 0.19794867854947756
    val_loss: 2.1986998868779897
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  dropout: 0.2
  num_blocks: 5
  num_params: 465994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/svhn_dropout_533616/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
