batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 17
  local_start: 2022-05-16_22:49:22
  local_stop: 2022-05-17_15:48:20
  program_exit: FAILURE
  stats:
    train_acc: 0.8615145228215768
    train_loss: 0.3946275417041031
    val_acc: 0.8440765212046711
    val_loss: 0.4505746515941742
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/fast_svhn_473006/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: SVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: SVHN
