batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 1
  local_start: 2022-05-14_17:01:27
  local_stop: 2022-05-14_17:50:54
  program_exit: FAILURE
  stats:
    train_acc: 0.3138785761083206
    train_loss: 2.000562542024776
    val_acc: 0.6495851259987707
    val_loss: 1.0246248654202634
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 3
  num_params: 269994
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_1_n1_469526/resnet20_0
param: param-files/LPResNet/RotSVHN/resnet20.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
