batch_size: 16
collate: batch
device: cuda
execution:
  epochs_completed: 40
  local_start: 2022-04-28_12:17:30
  local_stop: 2022-04-28_14:36:56
  program_exit: SUCCESS
  stats:
    train_acc: 0.9963333333333333
    train_loss: 0.01136528146117059
    val_acc: 0.9938
    val_loss: 0.02265691834473964
model:
  act_func: relu
  batch_norm: false
  classname: DeepLogPolarClassifier
  dropout: 0.2
  layer_params:
  - in_channels: 1
    kernel_size: 7
    lp_version: bilinear
    ntau: 8
    num_angles: 12
    out_channels: 32
    spatial_trim: 2
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 8
    num_angles: 12
    out_channels: 32
    spatial_trim: 2
    tau_max: 30
    tau_min: 1
    topk: 12
  - in_channels: 32
    kernel_size: 5
    lp_version: bilinear
    ntau: 8
    num_angles: 12
    out_channels: 32
    spatial_trim: 2
    tau_max: 30
    tau_min: 1
    topk: 12
  num_params: 81354
  out_classes: 10
  output: max
  type: logpolar
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/Deep_LP_train/mnist/full_mnist_angle_invariance/bilinear_trim_419059/30deg_rotations_tk12_trim_1
param: param-files/Deep-LP/MNIST/rotation_test/30deg_rotations_tk12_trim.yaml
train_data_dir:
  kwargs:
    root: data
    train: true
  type: FastMNIST
val_data_dir:
  kwargs:
    root: data
    train: false
  type: FastMNIST
