batch_size: 8
collate: batch
device: cuda
execution:
  epochs_completed: 10
  local_start: 2022-05-13_13:59:27
  local_stop: 2022-05-14_01:45:18
  program_exit: FAILURE
  stats:
    train_acc: 0.5745113561913081
    train_loss: 1.22968648050772
    val_acc: 0.6236555009219422
    val_loss: 1.1060429968812218
model:
  act_func: relu
  block: DeepLPBlock
  classname: LPResNet
  num_blocks: 5
  num_params: 465290
  out_classes: 10
  type: lp_resnet
num_epochs: 40
optimizer:
  params:
    lr: 0.001
  type: adam
out_dir: /geode2/home/u080/skarukas/Carbonate/SITH/out/LP_ResNet_train/rotsvhn/resnets_sub_imean_468517/resnet32_1
param: param-files/LPResNet/RotSVHN/resnet32.yaml
train_data_dir:
  kwargs:
    root: data
    split: train
  type: RotSVHN
val_data_dir:
  kwargs:
    root: data
    split: test
  type: RotSVHN
